on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo "this is ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo "this is ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_1,job_2]
    steps:
      - run: echo "this is ${{ github.job }}"
