name: First workflow

on:
  push: 
    branches:
       - main
jobs:
  example-jobs:
      env:
        github: ${{ tojson(github) }}
      if: github.
      strategy:
        matrix: 
          os: [ubuntu-latest, windows-latest]
          
      runs-on: ${{ matrix.os }}

      steps:
        - name: print a welcome message
          run: echo "welcome to our first job"

        - name: checkout repository
          uses: actions/checkout@v4.2.2

        - name: list repository files
          run: ls -la
