name: First workflow

on:
  push: 
    branches:
       - main
jobs:
  example-jobs:
      runs-on: ubuntu-latest

      steps:
        - name: print a welcome message
          run: echo "welcome to our first job"

        - name: checkout repository
          uses: actions/checkout@v4.2.2

        - name: list repository files
          run: ls -la
